# Generated by Django 4.1.3 on 2022-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_address_number_alter_person_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
    ]
