# Generated by Django 4.1.3 on 2022-11-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_person_age_alter_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/person'),
        ),
    ]
